lidar_with_mirror_pitch_controller:
    type  : position_controllers/JointPositionController
    joint : lidar_with_mirror_pitch_joint

lidar_with_mirror_roll_controller:
    type  : position_controllers/JointPositionController
    joint : lidar_with_mirror_roll_joint

lidar_with_mirror_mirror1_roll_controller:
    type  : position_controllers/JointPositionController
    joint : lidar_with_mirror_mirror1_roll_joint

lidar_with_mirror_mirror2_roll_controller:
    type  : position_controllers/JointPositionController
    joint : lidar_with_mirror_mirror2_roll_joint

lidar_with_mirror_prismatic_controller:
    type  : position_controllers/JointPositionController
    joint : lidar_with_mirror_prismatic_joint

caster_front_controller:
    type  : position_controllers/JointPositionController
    joint : caster_front_joint

wheel_hinge_controller:
    type  : position_controllers/JointPositionController
    joint : wheel_hinge

